name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Determine Go version
      id: go-version
      run: 'echo "value=$(cat .go-version)" >> $GITHUB_OUTPUT'

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "${{ steps.go-version.outputs.value }}"

    - name: Run solutions
      run: 'make run'
